version: "3.8"

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: artisan #change to your db.
      POSTGRES_USER: postgres #db username.
      POSTGRES_PASSWORD: postgres #db password.
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg_data:
